// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqygahlsaremdltcqlsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxeWdhaGxzYXJlbWRsdGNxbHN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyMDgzNDYsImV4cCI6MjA1Njc4NDM0Nn0.Z2-Xj5S4U-10Hv99eUUhwV8lsfPoLvmQpiD98F7y4i0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);